### registering new user

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "firstname":"Steve",
    "middlename":"patient",
    "lastname":"2",
    "email":"ondiekistephen00@gmail.com",
    "password":"12345678",
    "phone_number":"+254704453499"
}

### get all users
GET http://localhost:5000/api/user

###  login users
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email":"stevehot@gmail.com",
    "password":"1234578"
}

### add medical products    product_name,product_description,price, stock_quantity
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "product_name":"Clozole B",
    "product_description":"100mg/100ml",
    "price":"34",
    "stock_quantity":"300"
}

### get all the medical products 
GET http://localhost:5000/api/product
### get details of a single product 
GET http://localhost:5000/api/product/5f1e1c4d-62ef-48a2-9e12-3ab8f5604a16
