### registering new user

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "firstname":"Steve",
    "middlename":"patient",
    "lastname":"2",
    "email":"ondiekistephen00@gmail.com",
    "password":"12345678",
    "phone_number":"+254704453499"
}

### get all users
GET http://localhost:5000/api/user

###  login users
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email":"stevehot@gmail.com",
    "password":"12345678"
}