### registering new user

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "firstname":"Steve",
    "middlename":"O.",
    "lastname":"Omondi",
    "email":"omondistephen350@gmail.com",
    "password":"12345678",
    "phone_number":"+254704453499"
}

### get all users
GET http://localhost:5000/api/user

###  login users
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email":"omondistephen350@gmail.com",
    "password":"12345678"
}

### add medical products    product_name,product_description,price, stock_quantity
POST http://localhost:5000/api/product
Content-Type: application/json

{
    "product_name":"Clozole B",
    "product_description":"100mg/100ml",
    "price":"34",
    "stock_quantity":"300"
}

### get all the medical products 
GET http://localhost:5000/api/product
### get details of a single product 
GET http://localhost:5000/api/product/5f1e1c4d-62ef-48a2-9e12-3ab8f5604a16
### fetching all  products
GET http://localhost:5000/api/order
### make ordder
POST http://localhost:5000/api/order/fd745f82-48b6-4c19-87f3-290288496953
#### add item to cart
POST http://localhost:5000/api/cart/b8b24e93-4508-4776-b593-ad10989ec58e
Content-Type: application/json

{
    "product_id":"9984b608-36fd-47e2-a8cd-0bf7c54ac59a",
    "quantity":7
}

#### create a new medical order 
POST http://localhost:5000/api/order/5222ef99-29a3-4c30-bff9-1046cc9ecd1b
##### remove an item from cart 
DELETE http://localhost:5000/api/cart/9984b608-36fd-47e2-a8cd-0bf7c54ac59a
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjhiMjRlOTMtNDUwOC00Nzc2LWI1OTMtYWQxMDk4OWVjNThlIiwiZmlyc3RuYW1lIjoiU3RldmUiLCJlbWFpbCI6Im9tb25kaXN0ZXBoZW4zNTBAZ21haWwuY29tIiwiaWF0IjoxNzEyNjg0Mzk4LCJleHAiOjE3MTI3Mjc1OTh9.KTKKO4XUieDYK4qb1MfAQ_bV0OIUsCbnr8UII5dBc3g